[package]
name = "sample_lib"
version = "0.1.0"
authors = ["Horimatsu Takuya <new_woory@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
